### ISSUE TITLE
refactor main site link

### ISSUE THREAD

**Issue by zeehang** [dailybruin/lux#189]
planned: `mainsitearticleheader` uses a ton of links with
```css
text-decoration: none;
                color: ${dailyBruinBlue};

                :hover {
                  opacity: 0.75;
 }
```

We can refactor this into a `MainSiteLink` component - because link behavior and appearance in body text should be consistent across the entire site to promote good UX
